### ISSUE TITLE
방화벽설정

### ISSUE THREAD

**Issue by woonkchoi** [asw-dod/iptime-N104T#2]
방화벽 규칙설정하는 API가 있을까요?

**Comment by Piorosen** [comment]
@woonkchoi 아뇨, 따로 없습니다. 현재 아마, 현재 API는 더 이상 최신 아이피타임 공유기에서는 동작하지 않는것으로 알고 있습니다.
그래서 새롭게 만들거나 현재 펌웨어로 덮어 쓰셔야지 사용이 가능합니다.

**Comment by Piorosen** [comment]
@woonkchoi 따로 추가적인 질문이 없으시다면 이슈는 3일 내로 닫겟습니다.
